version: "3.9"

name: template-service

# Example API for images
services:
  grpc.proxy:
    image: ${ENVOY_GRPC_PROXY_IMAGE}
    container_name: ${ENVOY_GRPC_PROXY_HOSTNAME}
    healthcheck:
      test: "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/${ENVOY_GRPC_PROXY_INTERNAL_PORT}; exit $?;'"
      interval: 10s
      retries: 60
      start_period: 20s
      timeout: 10s
    volumes:
      - ./envoy/envoy-dev.yaml:/etc/envoy/envoy.yaml:ro
      - ./envoy/definitions/adempiere-report-engine-service.dsc:/data/descriptor.dsc:ro
    ports:
     - ${ENVOY_GRPC_PROXY_EXTERNAL_PORT}:${ENVOY_GRPC_PROXY_INTERNAL_PORT}
    networks:
    - shared_network

networks:
  shared_network:
    name: ${DEFAULT_NETWORK}

volumes:
  volume_postgres:
    name: ${POSTGRES_VOLUME}
